### ISSUE TITLE
Uncaught Error: read uint

### ISSUE THREAD

**Issue by btcpcs** [techjb/Vector-Tiles-Google-Maps#2]
![Capture](https://user-images.githubusercontent.com/69687675/132608669-a74c0852-2841-496f-9e3a-3a7c744223f6.PNG)

Thanks for this library. I am trying to load a vector tile layer generated from PostGIS. The layer works fine within a mapboxgl js client but I receive the error in the screenshot when trying to add it in one of the samples in the repo.
function InitVectorTiles() {
            var options = {
                url: "http://localhost:7800/public.testlayer/{z}/{x}/{y}.pbf",
                debug: true     
            };
            var mvtSource = new MVTSource(map, options);
            map.overlayMapTypes.insertAt(0, mvtSource);

Thanks

**Comment by techjb** [comment]
The problem is that in the library used to read the vector tiles, the float values (tag 5) are commented, then throw error:
https://github.com/SpatialServer/Leaflet.MapboxVectorTile/blob/master/dist/Leaflet.MapboxVectorTile.js#L766

I have uncommented it, and also the tag 2, as seen in this library:
https://github.com/mapbox/vector-tile-js/blob/master/lib/vectortilelayer.js#L45

It has not been tested, but it should works.
Please, let me know if the bug is fixed.
